import { useMemo, useRef, useState } from "react";
import type { VisualProfile, VisualSegment, VisualVertex } from "./types";

const example: VisualVertex[] = [
  { vertex_id: "v-001", x: -120, y: 0 }, { vertex_id: "v-002", x: -70, y: 0 },
  { vertex_id: "v-003", x: -55, y: 35 }, { vertex_id: "v-004", x: 55, y: 35 },
  { vertex_id: "v-005", x: 70, y: 0 }, { vertex_id: "v-006", x: 120, y: 0 },
];
export function exampleProfile(): VisualProfile { return { schema_version: 1, profile_id: "public-example-channel", name: "Public synthetic channel example", topology: "OPEN_PATH", closed: false, computational_seam_vertex_id: null, vertices: example, segments: example.slice(1).map((point, index) => ({ segment_id: `s-${String(index + 1).padStart(3, "0")}`, type: "LINE", start_vertex_id: example[index].vertex_id, end_vertex_id: point.vertex_id })), metadata: { source: "PUBLIC_SYNTHETIC_TEST", visual_only: true } }; }

type Props = { profile: VisualProfile; onChange: (profile: VisualProfile) => void };
type Tool = "SELECT" | "LINE" | "POLYLINE" | "ARC" | "PAN";

function arcPath(segment: VisualSegment, vertices: VisualVertex[]): string | null {
  if (segment.type !== "ARC" || !segment.center || !segment.radius) return null;
  const start = vertices.find((item) => item.vertex_id === segment.start_vertex_id); const end = vertices.find((item) => item.vertex_id === segment.end_vertex_id);
  if (!start || !end) return null;
  const a0 = Math.atan2(start.y - segment.center.y, start.x - segment.center.x); const a1 = Math.atan2(end.y - segment.center.y, end.x - segment.center.x);
  let delta = a1 - a0; if (segment.clockwise ? delta > 0 : delta < 0) delta += segment.clockwise ? -2 * Math.PI : 2 * Math.PI;
  const large = Math.abs(delta) > Math.PI ? 1 : 0; const sweep = segment.clockwise ? 0 : 1;
  return `M ${start.x} ${-start.y} A ${segment.radius} ${segment.radius} 0 ${large} ${sweep} ${end.x} ${-end.y}`;
}

export function ProfileSketcher({ profile, onChange }: Props) {
  const [tool, setTool] = useState<Tool>("SELECT"); const [selected, setSelected] = useState<string | null>(null); const [selectedSegment, setSelectedSegment] = useState<string | null>(null); const [past, setPast] = useState<VisualProfile[]>([]); const [future, setFuture] = useState<VisualProfile[]>([]); const [arcPoints, setArcPoints] = useState<Array<{ x: number; y: number }>>([]); const [zoom, setZoom] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const dragStart = useRef<VisualProfile | null>(null); const panStart = useRef<{ x: number; y: number } | null>(null);
  const points = profile.vertices;
  const bounds = useMemo(() => { const xs = points.map((p) => p.x); const ys = points.map((p) => p.y); return { minX: Math.min(...xs, -1), maxX: Math.max(...xs, 1), minY: Math.min(...ys, -1), maxY: Math.max(...ys, 1) }; }, [points]);
  const scale = Math.max(bounds.maxX - bounds.minX, bounds.maxY - bounds.minY, 1) * 0.12 / zoom;
  function commit(next: VisualProfile, snapshot = profile) { setPast((items) => [...items.slice(-49), snapshot]); setFuture([]); onChange(next); }
  function world(event: { clientX: number; clientY: number }, svg: SVGSVGElement): { x: number; y: number } { const rect = svg.getBoundingClientRect(); const width = bounds.maxX - bounds.minX + scale * 2; const height = bounds.maxY - bounds.minY + scale * 2; return { x: Math.round((((event.clientX - rect.left) / rect.width) * width + bounds.minX - scale - pan.x) * 100) / 100, y: Math.round(((-((event.clientY - rect.top) / rect.height) * height + bounds.maxY + scale - pan.y)) * 100) / 100 }; }
  function snapped(input: { x: number; y: number }): { x: number; y: number } { const grid = 5; let best = { x: Math.round(input.x / grid) * grid, y: Math.round(input.y / grid) * grid }; if (tool === "SELECT") return input; const endpoints = points.filter((point) => Math.hypot(point.x - input.x, point.y - input.y) < grid * 1.4); if (endpoints[0]) best = { x: endpoints[0].x, y: endpoints[0].y }; return best; }
  function addPoint(event: React.PointerEvent<SVGSVGElement>) { if (tool !== "LINE" && tool !== "POLYLINE" && tool !== "ARC") return; const input = snapped(world(event, event.currentTarget)); if (tool === "ARC") { const next = [...arcPoints, input]; if (next.length < 3) { setArcPoints(next); return; } const [start, through, end] = next; const determinant = 2 * (start.x * (through.y - end.y) + through.x * (end.y - start.y) + end.x * (start.y - through.y)); if (Math.abs(determinant) < 1e-6) { setArcPoints([]); return; } const center = { x: ((start.x ** 2 + start.y ** 2) * (through.y - end.y) + (through.x ** 2 + through.y ** 2) * (end.y - start.y) + (end.x ** 2 + end.y ** 2) * (start.y - through.y)) / determinant, y: ((start.x ** 2 + start.y ** 2) * (end.x - through.x) + (through.x ** 2 + through.y ** 2) * (start.x - end.x) + (end.x ** 2 + end.y ** 2) * (through.x - start.x)) / determinant }; const startId = points.at(-1)?.vertex_id ?? `v-${points.length + 1}`; const endId = `v-${points.length + 2}`; const startVertex = points.at(-1) ?? { vertex_id: startId, x: start.x, y: start.y }; const endVertex = { vertex_id: endId, x: end.x, y: end.y }; const radius = Math.hypot(start.x - center.x, start.y - center.y); commit({ ...profile, vertices: points.includes(startVertex) ? [...points, endVertex] : [...points, startVertex, endVertex], segments: [...profile.segments, { segment_id: `s-${profile.segments.length + 1}`, type: "ARC", start_vertex_id: startId, end_vertex_id: endId, center, radius, clockwise: false }] }); setArcPoints([]); return; } const id = `v-${points.length + 1}`; const nextPoint = { vertex_id: id, ...input }; const previous = points.at(-1); commit({ ...profile, vertices: [...points, nextPoint], segments: previous ? [...profile.segments, { segment_id: `s-${profile.segments.length + 1}`, type: "LINE", start_vertex_id: previous.vertex_id, end_vertex_id: id }] : profile.segments }); }
  function move(event: React.PointerEvent<SVGCircleElement>, id: string) { if (dragStart.current === null) return; const svg = event.currentTarget.ownerSVGElement; if (!svg) return; const input = world(event, svg); onChange({ ...profile, vertices: points.map((point) => point.vertex_id === id ? { ...point, x: input.x, y: input.y } : point) }); }
  function finishDrag() { if (dragStart.current) { setPast((items) => [...items.slice(-49), dragStart.current!]); setFuture([]); dragStart.current = null; } }
  function undo() { const previous = past.at(-1); if (!previous) return; setPast((items) => items.slice(0, -1)); setFuture((items) => [profile, ...items]); onChange(previous); }
  function redo() { const next = future[0]; if (!next) return; setFuture((items) => items.slice(1)); setPast((items) => [...items, profile]); onChange(next); }
  function deleteSelected() { if (selected) { const remaining = points.filter((point) => point.vertex_id !== selected); const segments = profile.segments.filter((segment) => segment.start_vertex_id !== selected && segment.end_vertex_id !== selected); commit({ ...profile, vertices: remaining, segments, computational_seam_vertex_id: profile.computational_seam_vertex_id === selected ? null : profile.computational_seam_vertex_id }); setSelected(null); return; } if (selectedSegment) { commit({ ...profile, segments: profile.segments.filter((segment) => segment.segment_id !== selectedSegment) }); setSelectedSegment(null); } }
  function resetExample() { setPast([]); setFuture([]); onChange(exampleProfile()); }
  function toggleClosed() { const closed = profile.topology === "OPEN_PATH"; commit({ ...profile, topology: closed ? "CLOSED_CONTOUR" : "OPEN_PATH", closed, computational_seam_vertex_id: closed ? profile.vertices[0]?.vertex_id ?? null : null }); }
  function mirror(horizontal: boolean) { commit({ ...profile, vertices: points.map((point) => ({ ...point, ...(horizontal ? { y: -point.y } : { x: -point.x }) })) }); }
  function rotate() { commit({ ...profile, vertices: points.map((point) => ({ ...point, x: -point.y, y: point.x })) }); }
  const viewBox = `${bounds.minX - scale + pan.x} ${-bounds.maxY - scale - pan.y} ${bounds.maxX - bounds.minX + scale * 2} ${bounds.maxY - bounds.minY + scale * 2}`;
  return <div><div className="visual-toolbar">{(["SELECT", "LINE", "POLYLINE", "ARC", "PAN"] as Tool[]).map((item) => <button key={item} className={tool === item ? "active" : ""} onClick={() => setTool(item)}>{item}</button>)}<button onClick={deleteSelected} disabled={!selected && !selectedSegment}>Delete</button><button onClick={undo} disabled={!past.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button><button onClick={() => setZoom((value) => value * 1.25)}>Zoom +</button><button onClick={() => setZoom((value) => Math.max(.25, value / 1.25))}>Zoom −</button><button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}>Fit view</button><button onClick={() => mirror(false)}>Mirror H</button><button onClick={() => mirror(true)}>Mirror V</button><button onClick={rotate}>Rotate 90°</button><button onClick={toggleClosed}>{profile.topology === "OPEN_PATH" ? "Close contour" : "Open contour"}</button><button onClick={() => selected && commit({ ...profile, computational_seam_vertex_id: selected })} disabled={profile.topology !== "CLOSED_CONTOUR" || !selected}>Set seam</button><button onClick={resetExample}>Load Example</button><button onClick={() => { setPast([]); setFuture([]); onChange({ ...profile, vertices: [], segments: [], computational_seam_vertex_id: null, topology: "OPEN_PATH", closed: false }); }}>Clear</button></div>
    <svg role="img" aria-label="Visual profile sketcher" viewBox={viewBox} onPointerDown={(event) => { if (tool === "PAN") panStart.current = { x: event.clientX, y: event.clientY }; else addPoint(event); }} onPointerMove={(event) => { if (panStart.current) { setPan((value) => ({ x: value.x + (event.clientX - panStart.current!.x) * scale / 30, y: value.y + (event.clientY - panStart.current!.y) * scale / 30 })); panStart.current = { x: event.clientX, y: event.clientY }; } }} onPointerUp={() => { panStart.current = null; finishDrag(); }} onWheel={(event) => { event.preventDefault(); setZoom((value) => Math.max(.25, Math.min(8, value * (event.deltaY < 0 ? 1.1 : .9)))); }} style={{ width: "100%", minHeight: 360, border: "1px solid #b7c0ca", background: "#fbfcfd", touchAction: "none" }}>
      <path d={`M ${bounds.minX - scale * 2} 0 L ${bounds.maxX + scale * 2} 0 M 0 ${-bounds.minY - scale * 2} L 0 ${-bounds.maxY + scale * 2}`} stroke="#d9e0e6" strokeWidth={scale * .04} />
      {profile.segments.map((segment) => { const a = points.find((p) => p.vertex_id === segment.start_vertex_id); const b = points.find((p) => p.vertex_id === segment.end_vertex_id); if (!a || !b) return null; const path = segment.type === "ARC" ? arcPath(segment, points) : `M ${a.x} ${-a.y} L ${b.x} ${-b.y}`; return <path key={segment.segment_id} data-testid={segment.type === "ARC" ? "visual-arc-path" : "visual-line-path"} d={path ?? undefined} fill="none" stroke={selectedSegment === segment.segment_id ? "#c46b00" : "#144d7a"} strokeWidth={scale * .18} onPointerDown={(event) => { event.stopPropagation(); setSelectedSegment(segment.segment_id); setSelected(null); }} />; })}
      {profile.topology === "CLOSED_CONTOUR" && profile.computational_seam_vertex_id && <circle cx={points.find((p) => p.vertex_id === profile.computational_seam_vertex_id)?.x} cy={-(points.find((p) => p.vertex_id === profile.computational_seam_vertex_id)?.y ?? 0)} r={scale * .7} fill="none" stroke="#bd3d3d" strokeWidth={scale * .12} />}
      {points.map((point) => <circle key={point.vertex_id} cx={point.x} cy={-point.y} r={scale * .35} fill={selected === point.vertex_id ? "#c46b00" : "#fff"} stroke="#144d7a" strokeWidth={scale * .12} onPointerDown={(event) => { event.stopPropagation(); setSelected(point.vertex_id); setSelectedSegment(null); if (tool === "SELECT") { dragStart.current = profile; (event.currentTarget as SVGCircleElement).setPointerCapture(event.pointerId); } }} onPointerMove={(event) => move(event, point.vertex_id)} onPointerUp={finishDrag} />)}
      {arcPoints.map((point, index) => <circle key={`arc-${index}`} cx={point.x} cy={-point.y} r={scale * .25} fill="#c46b00" />)}
    </svg><p>Tool: {tool}. Vertices: {points.length}. Segments: {profile.segments.length}. Topology: {profile.topology}. Computational seam: {profile.computational_seam_vertex_id ?? "not set"}. Grid snap: 5 units; endpoint snap enabled.</p>
    {selected && <label>Selected vertex X <input aria-label="Selected vertex X" type="number" value={points.find((point) => point.vertex_id === selected)?.x ?? 0} onChange={(event) => commit({ ...profile, vertices: points.map((point) => point.vertex_id === selected ? { ...point, x: Number(event.target.value) } : point) })} /> Y <input aria-label="Selected vertex Y" type="number" value={points.find((point) => point.vertex_id === selected)?.y ?? 0} onChange={(event) => commit({ ...profile, vertices: points.map((point) => point.vertex_id === selected ? { ...point, y: Number(event.target.value) } : point) })} /></label>}
    {selectedSegment && <p>Selected segment: {selectedSegment}. {profile.segments.find((segment) => segment.segment_id === selectedSegment)?.type === "ARC" ? "Arc radius and direction are stored in the profile schema." : "Line segment."}</p>}
  </div>;
}
