import { useEffect, useMemo, useState } from "react";
import type { VisualProfile, VisualVertex } from "./types";

const example: VisualVertex[] = [
  { vertex_id: "v-001", x: -120, y: 0 }, { vertex_id: "v-002", x: -70, y: 0 },
  { vertex_id: "v-003", x: -55, y: 35 }, { vertex_id: "v-004", x: 55, y: 35 },
  { vertex_id: "v-005", x: 70, y: 0 }, { vertex_id: "v-006", x: 120, y: 0 },
];

export function exampleProfile(): VisualProfile { return { schema_version: 1, profile_id: "public-example-channel", name: "Public synthetic channel example", topology: "OPEN_PATH", closed: false, computational_seam_vertex_id: null, vertices: example, segments: example.slice(1).map((point, index) => ({ segment_id: `s-${String(index + 1).padStart(3, "0")}`, type: "LINE", start_vertex_id: example[index].vertex_id, end_vertex_id: point.vertex_id })), metadata: { source: "PUBLIC_SYNTHETIC_TEST", visual_only: true } }; }

type Props = { profile: VisualProfile; onChange: (profile: VisualProfile) => void; };
export function ProfileSketcher({ profile, onChange }: Props) {
  const [tool, setTool] = useState("SELECT");
  const [selected, setSelected] = useState<string | null>(null);
  const [past, setPast] = useState<VisualProfile[]>([]);
  const [future, setFuture] = useState<VisualProfile[]>([]);
  const [dragging, setDragging] = useState<string | null>(null);
  const [arcPoints, setArcPoints] = useState<Array<{ x: number; y: number }>>([]);
  const points = profile.vertices;
  const bounds = useMemo(() => { const xs = points.map((p) => p.x); const ys = points.map((p) => p.y); return { minX: Math.min(...xs, -1), maxX: Math.max(...xs, 1), minY: Math.min(...ys, -1), maxY: Math.max(...ys, 1) }; }, [points]);
  function commit(next: VisualProfile) { setPast((items) => [...items.slice(-49), profile]); setFuture([]); onChange(next); }
  function addPoint(event: React.MouseEvent<SVGSVGElement>) { if (tool !== "LINE" && tool !== "POLYLINE" && tool !== "ARC") return; const svg = event.currentTarget.getBoundingClientRect(); const x = ((event.clientX - svg.left) / svg.width) * (bounds.maxX - bounds.minX) + bounds.minX; const y = (1 - (event.clientY - svg.top) / svg.height) * (bounds.maxY - bounds.minY) + bounds.minY; if (tool === "ARC") { const next = [...arcPoints, { x, y }]; if (next.length < 3) { setArcPoints(next); return; } const [start, through, end] = next; const determinant = 2 * (start.x * (through.y - end.y) + through.x * (end.y - start.y) + end.x * (start.y - through.y)); if (Math.abs(determinant) < 1e-6) { setArcPoints([]); window.alert("Arc rejected: the three points are nearly collinear."); return; } const center = { x: (start.x * start.x + start.y * start.y) * (through.y - end.y) + (through.x * through.x + through.y * through.y) * (end.y - start.y) + (end.x * end.x + end.y * end.y) * (start.y - through.y) }; const cy = ((start.x * start.x + start.y * start.y) * (end.x - through.x) + (through.x * through.x + through.y * through.y) * (start.x - end.x) + (end.x * end.x + end.y * end.y) * (through.x - start.x)) / determinant; const resolvedCenter = { x: center.x / determinant, y: cy }; const startId = points.at(-1)?.vertex_id ?? `v-${String(points.length + 1).padStart(3, "0")}`; const endId = `v-${String(points.length + 2).padStart(3, "0")}`; const startVertex = points.at(-1) ?? { vertex_id: startId, x: start.x, y: start.y }; const endVertex = { vertex_id: endId, x: end.x, y: end.y }; const radius = Math.hypot(start.x - resolvedCenter.x, start.y - resolvedCenter.y); commit({ ...profile, vertices: points.includes(startVertex) ? [...points, endVertex] : [...points, startVertex, endVertex], segments: [...profile.segments, { segment_id: `s-${String(profile.segments.length + 1).padStart(3, "0")}`, type: "ARC", start_vertex_id: startId, end_vertex_id: endId, center: resolvedCenter, radius, clockwise: false }] }); setArcPoints([]); return; } const id = `v-${String(points.length + 1).padStart(3, "0")}`; const vertices = [...points, { vertex_id: id, x: Math.round(x * 100) / 100, y: Math.round(y * 100) / 100 }]; const previous = points.at(-1); const segments = previous ? [...profile.segments, { segment_id: `s-${String(profile.segments.length + 1).padStart(3, "0")}`, type: "LINE" as const, start_vertex_id: previous.vertex_id, end_vertex_id: id }] : profile.segments; commit({ ...profile, vertices, segments }); }
  function move(event: React.MouseEvent<SVGCircleElement>, id: string) { if (!dragging || dragging !== id) return; const svg = event.currentTarget.ownerSVGElement?.getBoundingClientRect(); if (!svg) return; const x = ((event.clientX - svg.left) / svg.width) * (bounds.maxX - bounds.minX) + bounds.minX; const y = (1 - (event.clientY - svg.top) / svg.height) * (bounds.maxY - bounds.minY) + bounds.minY; onChange({ ...profile, vertices: points.map((point) => point.vertex_id === id ? { ...point, x, y } : point) }); }
  function undo() { const previous = past.at(-1); if (!previous) return; setPast((items) => items.slice(0, -1)); setFuture((items) => [profile, ...items]); onChange(previous); }
  function redo() { const next = future[0]; if (!next) return; setFuture((items) => items.slice(1)); setPast((items) => [...items, profile]); onChange(next); }
  const scale = Math.max(bounds.maxX - bounds.minX, bounds.maxY - bounds.minY, 1) * 0.12;
  return <div><div className="visual-toolbar">{["SELECT", "LINE", "POLYLINE", "ARC"].map((item) => <button key={item} className={tool === item ? "active" : ""} onClick={() => setTool(item)}>{item}</button>)}<button onClick={undo} disabled={!past.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button><button onClick={() => { setPast([]); setFuture([]); onChange(exampleProfile()); }}>Load Example</button><button onClick={() => commit({ ...profile, topology: profile.topology === "OPEN_PATH" ? "CLOSED_CONTOUR" : "OPEN_PATH", closed: profile.topology === "OPEN_PATH", computational_seam_vertex_id: profile.topology === "OPEN_PATH" ? profile.vertices[0]?.vertex_id ?? null : null })}>Open/Close</button></div><svg role="img" aria-label="Visual profile sketcher" viewBox={`${bounds.minX - scale} ${-bounds.maxY - scale} ${bounds.maxX - bounds.minX + scale * 2} ${bounds.maxY - bounds.minY + scale * 2}`} onClick={addPoint} style={{ width: "100%", minHeight: 320, border: "1px solid #b7c0ca", background: "#fbfcfd" }}>{profile.segments.map((segment) => { const a = points.find((p) => p.vertex_id === segment.start_vertex_id); const b = points.find((p) => p.vertex_id === segment.end_vertex_id); return a && b ? <line key={segment.segment_id} x1={a.x} y1={-a.y} x2={b.x} y2={-b.y} stroke="#144d7a" strokeWidth={scale * .18} /> : null; })}{points.map((point) => <circle key={point.vertex_id} cx={point.x} cy={-point.y} r={scale * .35} fill={selected === point.vertex_id ? "#c46b00" : "#fff"} stroke="#144d7a" strokeWidth={scale * .12} onMouseDown={() => { setSelected(point.vertex_id); setDragging(point.vertex_id); }} onMouseUp={() => setDragging(null)} onMouseMove={(event) => move(event, point.vertex_id)} />)}</svg><p>Tool: {tool}. Vertices: {points.length}. Segments: {profile.segments.length}. Topology: {profile.topology}. Computational seam: {profile.computational_seam_vertex_id ?? "not set"}</p></div>;
}
