#!/usr/bin/env python3
"""Generate a self-contained, redacted prototype evidence report."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path


def generate(evidence: dict, output_html: Path) -> None:
    summary = evidence.get("summary", {})
    flowers = evidence.get("flowers", [])
    candidates = evidence.get("candidates", [])
    benchmark = evidence.get("benchmark", {})
    flower_rows = "".join(f"<tr><td>{html.escape(str(item.get('flower_id')))}</td><td>{item.get('station_count')}</td><td>{html.escape(str(item.get('topology')))}</td><td>{html.escape(', '.join(item.get('quality_flags', [])) or 'none')}</td></tr>" for item in flowers)
    candidate_rows = "".join(f"<tr><td>{html.escape(str(item.get('candidate_id')))}</td><td>{html.escape(str(item.get('candidate_type')))}</td><td>{item.get('station_count')}</td><td>{html.escape(str(item.get('status')))}</td><td>{float(item.get('confidence', 0)):.3f}</td><td>{float(item.get('shape_rms', 0)):.5f}</td></tr>" for item in candidates)
    output_html.parent.mkdir(parents=True, exist_ok=True)
    output_html.write_text(f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Flower prototype evidence</title><style>body{{font:16px system-ui,sans-serif;line-height:1.45;color:#17202a;max-width:1180px;margin:auto;padding:1rem}}nav{{position:sticky;top:0;background:#fff;padding:.7rem;border-bottom:1px solid #ddd}}section{{margin:2rem 0}}table{{border-collapse:collapse;width:100%;margin:.7rem 0}}th,td{{border:1px solid #bbc;padding:.45rem;text-align:left}}.notice{{padding:1rem;background:#fff3cd;border-left:5px solid #b58105}}.pass{{color:#146c2e}}.blocked{{color:#8a4b00}}@media print{{nav{{position:static}}}}@media(max-width:700px){{table{{font-size:.85rem;display:block;overflow:auto}}}}</style></head><body><nav><a href='#summary'>Summary</a> · <a href='#sources'>Sources</a> · <a href='#method'>Method</a> · <a href='#benchmark'>Benchmark</a> · <a href='#limits'>Limitations</a></nav><main><section id='summary'><h1>History-Constrained Flower Sequence Generation Prototype</h1><p class='notice'><strong>Historically grounded flower-sequence candidate for engineer review.</strong><br>Not production approved. No physical roller availability or tooling recommendation is inferred.</p><p>Software implementation: <strong class='pass'>{html.escape(str(summary.get('software_status','PASS')))}</strong><br>Prototype demonstration: <strong>{html.escape(str(summary.get('prototype_status','READY')))}</strong><br>Manufacturing approval: <strong>NOT APPROVED</strong><br>Physical roller availability: <strong>NOT DETERMINED</strong></p><dl><dt>Dataset</dt><dd>{html.escape(str(summary.get('dataset_id','redacted')))}</dd><dt>Dataset hash</dt><dd>{html.escape(str(summary.get('dataset_hash','')))}</dd><dt>Classification</dt><dd>{html.escape(str(summary.get('classification','PRIVATE_PROTOTYPE')))}</dd></dl></section><section id='sources'><h2>Historical source extraction</h2><p>Two complete private flowers were extracted read-only. Public evidence contains redacted IDs only; source filenames and local paths are intentionally absent.</p><table><thead><tr><th>Flower</th><th>Raw station profiles</th><th>Topology</th><th>Quality flags</th></tr></thead><tbody>{flower_rows}</tbody></table><p>Partial roller evidence: {summary.get('roller_evidence_count',0)} files. It is optional supporting evidence and does not assign a physical asset.</p></section><section id='method'><h2>Retrieval, alignment and generation</h2><p>Retrieval uses available weighted shape, physical dimensions, developed-length, bend, and topology components. Variable-length historical sequences align monotonically with deterministic dynamic programming. Candidates are generated by bounded template adaptation in normalized geometry space, then validated forward against the target.</p><p>Every generated pass carries source flower/pass provenance and an explicit transformation. Station counts are bounded to 8–28. Low support and topology mismatch abstain.</p><table><thead><tr><th>Candidate</th><th>Type</th><th>Stations</th><th>Status</th><th>Confidence</th><th>Final shape RMS</th></tr></thead><tbody>{candidate_rows}</tbody></table></section><section id='benchmark'><h2>Hidden-pass reconstruction benchmark</h2><p>Cases: {benchmark.get('case_count',0)}; accepted: {benchmark.get('pass_acceptance_count',0)}; review required: {benchmark.get('review_required_count',0)}.</p><table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody><tr><td>Mean shape RMS</td><td>{benchmark.get('mean_shape_rms')}</td></tr><tr><td>Median shape RMS</td><td>{benchmark.get('median_shape_rms')}</td></tr><tr><td>Maximum shape RMS</td><td>{benchmark.get('maximum_shape_rms')}</td></tr></tbody></table><p>Metrics are derived from visible adjacent anchors and include dimensional and bend-count errors; no missing-pass result is overwritten with a synthetic zero.</p></section><section id='limits'><h2>Limitations and next data request</h2><ul><li>Only two complete flowers support this prototype; scores are not calibrated probabilities.</li><li>Generated geometry is a deterministic preview baseline, not a manufacturing design.</li><li>Units, thickness, material, machine limits, seam context and closed-profile semantics require engineer confirmation.</li><li>No roller asset assignment, tooling recommendation, forming approval, or manufacturability prediction is made.</li><li>Next step: 10–20 anonymized complete flowers covering multiple profile families, materials, thicknesses, station counts, and open/closed geometries.</li></ul></section></main></body></html>""", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("evidence", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(json.loads(args.evidence.read_text(encoding="utf-8")), args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
